name: Scrape Casa Jorge

on:
  schedule:
    - cron: "0 0 1 * *"  # Se ejecuta el día 1 de cada mes a las 00:00 UTC
  workflow_dispatch:  # Permite ejecución manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso para depurar: muestra la lista de archivos en la raíz.
      - name: List repository files (debug)
        run: ls -la

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        # Ajustado para ejecutar "scraping_casajorge.py" (sin guion).
        run: python scraping_casajorge.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: productos-csv
          path: productos.csv